services:
  - type: web
    name: tradingview-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7580068850:AAHHBhP8uJGQUTnSZlD5C7vGgm_twR1uC0s
      - key: CHAT_ID
        value: your_chat_id_here
