services:
  - type: web
    name: tradingview-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: your_bot_token_here
      - key: CHAT_ID
        value: your_chat_id_here